version: '3'
services:
    web-front-end:
      image: razaanis/react-front-end:2
      ports:
        - "80:3000"
      depends_on:
        - "couchdb"
      environment:
        - API_CONNECTION_IP=172.17.0.1
    expressapi:
      image: razaanis/node-express-api:2
      ports:
        - "3001:3001"
      depends_on:
        - "couchdb"
        - "web-front-end"
      links:
        - "couchdb"
      environment:
        - DATABASE_IP=172.17.0.1
        - GMAIL_ACCOUNT_EMAIL=abc@gmail.com
        - GMAIL_ACCOUNT_PASSWORD=abc
    couchdb:
      container_name: couchdb
      image: razaanis/couchdb-database:2
      ports:
      - "5984:5984"
      - "5986:5986"
      environment:
      - COUCHDB_USER=razaanis123
      - COUCHDB_PASSWORD=abc123
