apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: web-front-end
  name: web-front-end
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web-front-end
    spec:
      containers:
      - env:
        - name: API_CONNECTION_IP
          value: 172.17.0.1
        image: razaanis/react-front-end:4
        name: web-front-end
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
